# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Allow local connections
local   all             all                                     trust

# Allow replication connection from the replica
host    replication     replicator      0.0.0.0/0               trust


# Allow all users to connect from any IP (for local dev only!)
host    all             all             0.0.0.0/0               trust
