# Listen on all IPs
listen_addresses = '*'

# WAL level must be set to 'replica' for streaming replication
wal_level = replica

# Max number of replication connections
max_wal_senders = 10

# Minimum retention of WAL files
wal_keep_size = 64MB

# Allow replication slots
hot_standby = on
